export const ROLES = {
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  EMPLOYEE: "EMPLOYEE"
};

export const APPROVAL_RULE_MODE = {
  PERCENTAGE: "PERCENTAGE",
  SPECIFIC_APPROVER: "SPECIFIC_APPROVER",
  HYBRID: "HYBRID"
};

export const EXPENSE_STATUS = {
  DRAFT: "DRAFT",
  IN_REVIEW: "IN_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED"
};
