export const permissionMap = {
    ADMIN: ["VIEW_ALL_EXPENSES", "OVERRIDE_APPROVALS", "SWITCH_ROLES"],
    MANAGER: ["VIEW_TEAM_EXPENSES", "APPROVE_EXPENSES"],
    EMPLOYEE: ["CREATE_EXPENSE", "VIEW_OWN_EXPENSES"]
};
